services:
  - name: youtube-summarizer
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render's dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
